name: online-resume

services:
    # https://github.com/FlorianLeChat/Online-Resume
    node:
        image: online-resume
        develop:
            watch:
                - path: .
                  action: sync
                  target: /usr/src/app
                  ignore:
                    - node_modules/
                - path: package-lock.json
                  action: rebuild
        healthcheck:
            test: wget -O - http://127.0.0.1:5173
            retries: 3
            timeout: 5s
        build:
            context: .
            dockerfile: ./Dockerfile
        ports:
            - "5173:5173"